### ISSUE TITLE
Add SonarQube

### ISSUE THREAD

**Issue by valentinacupac** [valentinacupac/sandbox-java#5]
See instructions on https://github.com/valentinacupac/banking-kata-java/issues/93

**Comment by JoaoCipriano** [comment]
Hi @valentinacupac! I've seen the latest commits and I believe that there are only two things left:
* Set the environment `development` at SonarCloud workflow; this step will keep the SONAR_TOKEN secret available. Example https://github.com/JoaoCipriano/sandbox-java/blob/e08e3b1b3621e3613c4f33bd6cc3e7b7cc193d55/.github/workflows/sonar_build.yml#L12
* Update the sonar property "sonar.host" to "sonar.host.url"; this step fixes the SonarQube server [http://localhost:9000] can not be reached error.

**Comment by valentinacupac** [comment]
Thanks @JoaoCipriano, I updated it, now it works.
